const mongoose = require('mongoose');

const FormSchema = new mongoose.Schema({
    owner: { type: mongoose.Schema.Types.ObjectId, ref: 'User', required: true },
    title: { type: String, required: true },
    description: { type: String },
    schema: { type: Object, required: true }, // The JSON schema generated by AI
    purpose: { type: String }, // For semantic search
    createdAt: { type: Date, default: Date.now }
});

module.exports = mongoose.model('Form', FormSchema);
